name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
jobs:
  build-and-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --global yarn
       
      - name: yarn build
        env: 
          GIT_USER: ${{ TeamAte92 }}
        run: |
         yarn install
         yarn build
         git remote add origin https://@github.com/Teamate92/website-v3.git
         yarn deploy
